// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        int32
	RoundID   int32
	RoundTime float64
	EventTime pgtype.Timestamp
	EventType string
	EventData []byte
}

type Round struct {
	ID        int32
	Map       string
	StartTime pgtype.Timestamp
	EndTime   pgtype.Timestamp
}

type User struct {
	Nickname  string
	Steamid64 int64
}
